name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk/svg-only@fork-add-background
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          color_snake: '#00FFAA'
          color_dots: '#222222,#333333,#444444,#666666,#888888'
          background: '#0d1117'  # <- Fundo escuro para combinar com o tema dark

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animation with dark background
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
